# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.delete_all
Quote.delete_all

puts "Seeding users..."
User.create!(username: "mbrowne", score: 3, weighted_score: 2.5)
User.create!(username: "moviefan11", score: 1, weighted_score: 0.75)
User.create!(username: "ilikemovies", score: 10, weighted_score: 9)

puts "Seeding quotes..."
Quote.create!(quote: "Frankly, my dear, I don't give a damn.", character: "Rhett Butler", actor: "Clark Gable", movie: "Gone with the Wind", year: 1939)
Quote.create!(quote: "I'm going to make him an offer he can't refuse.", character: "Vito Corleogne", actor: "Marlon Brando", movie: "The Godfather", year: 1972)
Quote.create!(quote:  "You don't understand! I could've had class. I could've been a contender. I could've been somebody, instead of a bum, which is what I am.", character: "Terry Malloy", actor: "Marlon Brando", movie: "On the Waterfront", year: 1954)
Quote.create!(quote: "Toto, I've a feeling we're not in Kansas anymore.", character: "Dorothy Gale", actor: "Judy Garland", movie: "The Wizard of Oz", year: 1939)
Quote.create!(quote: "Here's looking at you, kid.", character: "Rick Blaine", actor: "Humphrey Bogart", movie: "Casablanca", year: 1942)
Quote.create!(quote: "Go ahead, make my day.", character: "Harry Callahan", actor: "Clint Eastwood", movie: "Sudden Impact", year: 1983)
Quote.create!(quote: "All right, Mr. DeMille, I'm ready for my close-up.", character: "Norma Desmond", actor: "Gloria Swanson", movie: "Sunset Boulevard", year: 1950)
Quote.create!(quote: "May the Force be with you.", character: "Han Solo", actor: "Harrison Ford", movie: "Star Wars", year: 1977)
Quote.create!(quote: "Fasten your seatbelts. It's going to be a bumpy night.", character: "Margo Channing", actor: "Bette Davis", movie: "All About Eve", year: 1950)
Quote.create!(quote: "You talkin' to me?", character: "Travis Bickle", actor: "Robert De Niro", movie: "Taxi Driver", year: 1976)
Quote.create!(quote: "What we've got here is failure to communicate.", character: "Captain", actor: "Strother Martin", movie: "Cool Hand Luke", year: 1967)
Quote.create!(quote: "I love the smell of napalm in the morning.", character: "Lt. Col. Bill Kilgore", actor: "Robert Duvall", movie: "Apocalypse Now", year: 1979)
Quote.create!(quote: "Love means never having to say you're sorry.", character: "Jennifer Cavalleri", actor: "Ali MacGraw", movie: "Love Story", year: 1970)
Quote.create!(quote: "The stuff that dreams are made of.", character: "Sam Spade", actor: "Humphrey Bogart", movie: "The Maltese Falcon", year: 1941)
Quote.create!(quote: "E.T. phone home.", character: "E.T.", actor: "Pat Welsh", movie: "E.T. the Extra-Terrestrial", year: 1982)
Quote.create!(quote: "They call me Mister Tibbs!", character: "Virgil Tibbs", actor: "Sidney Poitier", movie: "In the Heat of the Night", year: 1967)
Quote.create!(quote: "Rosebud.", character: "Charles Foster Kane", actor: "Orson Welles", movie: "Citizen Kane", year: 1941)
Quote.create!(quote: "Made it, Ma! Top of the world!", character: "Arthur 'Cody' Jarrett", actor: "James Cagney", movie: "White Heat", year: 1949)
Quote.create!(quote: "I'm as mad as hell, and I'm not going to take this anymore!", character: "Howard Beale", actor: "Peter Finch", movie: "Network", year: 1976)
Quote.create!(quote: "Louis, I think this is the beginning of a beautiful friendship.", character: "Rick Blaine", actor: "Humphrey Bogart", movie: "Casablanca", year: 1942)
Quote.create!(quote: "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.", character: "Hannibal Lecter", actor: "Anthony Hopkins", movie: "The Silence of the Lambs", year: 1991)
Quote.create!(quote: "Bond. James Bond.", character: "James Bond", actor: "Sean Connery", movie: "Dr. No", year: 1962)
Quote.create!(quote: "There's no place like home.", character: "Dorothy Gale", actor: "Judy Garland", movie: "The Wizard of Oz", year: 1939)
Quote.create!(quote: "I am big! It's the pictures that got small.", character: "Norma Desmond", actor: "Gloria Swanson", movie: "Sunset Boulevard", year: 1950)
Quote.create!(quote: "Show me the money!", character: "Rod Tidwell", actor: "Cuba Gooding Jr.", movie: "Jerry Maguire", year: 1996)
Quote.create!(quote: "Why don't you come up sometime and see me?", character: "Lady Lou", actor: "Mae West", movie: "She Done Him Wrong", year: 1933)
Quote.create!(quote: "I'm walkin' here! I'm walkin' here!", character: "'Ratso' Rizzo", actor: "Dustin Hoffman", movie: "Midnight Cowboy", year: 1969)
Quote.create!(quote: "Play it, Sam. Play 'As Time Goes By.'", character: "Ilsa Lund", actor: "Ingrid Bergman", movie: "Casablanca", year: 1942)
Quote.create!(quote: "You can't handle the truth!", character: "Col. Nathan R. Jessup", actor: "Jack Nicholson", movie: "A Few Good Men", year: 1992)
Quote.create!(quote: "I want to be alone.", character: "Grusinskaya", actor: "Greta Garbo", movie: "Grand Hotel", year: 1932)
Quote.create!(quote: "After all, tomorrow is another day!", character: "Scarlett O'Hara", actor: "Vivien Leigh", movie: "Gone with the Wind", year:1939)
Quote.create!(quote: "Round up the usual suspects.", character: "Capt. Louis Renault", actor: "Claude Rains", movie: "Casablanca", year: 1942)
Quote.create!(quote: "I'll have what she's having.", character: "Customer", actor: "Estelle Reiner", movie: "When Harry Met Sally...", year: 1989)
Quote.create!(quote: "You know how to whistle, don't you, Steve? You just put your lips together and blow.", character: "Marie 'Slim' Browning", actor: "Lauren Bacall", movie: "To Have and Have Not", year: 1944)
Quote.create!(quote: "You're gonna need a bigger boat.", character: "Martin Brody", actor: "Roy Scheider", movie: "Jaws", year: 1975)
Quote.create!(quote: "Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!", character: "Gold Hat", actor: "Alfonso Bedoya", movie: "The Treasure of the Sierra Madre", year: 1948)
Quote.create!(quote: "I'll be back", character: "The Terminator", actor: "Arnold Schwarzenegger", movie: "The Terminator", year: 1984)
Quote.create!(quote: "Today, I consider myself the luckiest man on the face of the Earth.", character: "Lou Gehrig", actor: "Gary Cooper", movie: "The Pride of the Yankees", year: 1942)
Quote.create!(quote: "If you build it, he will come.", character: "Shoeless Joe Jackson", actor: "Ray Liotta (voice)", movie: "Field of Dreams", year: 1989)
Quote.create!(quote: "Mama always said life was like a box of chocolates. You never know what you're gonna get.", character: "Forrest Gump", actor: "Tom Hanks", movie: "Forrest Gump", year: 1994)
Quote.create!(quote: "We rob banks.", character: "Clyde Barrow", actor: "Warren Beatty", movie: "Bonnie and Clyde", year: 1967)
Quote.create!(quote: "Plastics.", character: "Mr. Maguire", actor: "Walter Brooke", movie: "The Graduate", year: 1967)
Quote.create!(quote: "We'll always have Paris.", character: "Rick Blaine", actor: "Humphrey Bogart", movie: "Casablanca", year: 1942)
Quote.create!(quote: "I see dead people.", character: "Cole Sear", actor: "Haley Joel Osment", movie: "The Sixth Sense", year: 1999)
Quote.create!(quote: "Stella! Hey, Stella!", character: "Stanley Kowalski", actor: "Marlon Brando", movie: "A Streetcar Named Desire", year: 1951)
Quote.create!(quote: "Oh, Jerry, don't let's ask for the moon. We have the stars.", character: "Charlotte Vale", actor: "Bette Davis", movie: "Now, Voyager", year: 1942)
Quote.create!(quote: "Shane. Shane. Come back!", character: "Joey Starrett", actor: "Brandon De Wilde", movie: "Shane", year: 1953)
Quote.create!(quote: "Well, nobody's perfect.", character: "Osgood Fielding III", actor: "Joe E. Brown", movie: "Some Like It Hot", year: 1959)
Quote.create!(quote: "It's alive! It's alive!", character: "Henry Frankenstein", actor: "Colin Clive", movie: "Frankenstein", year: 1931)
Quote.create!(quote: "Houston, we have a problem.", character: "Jim Lovell", actor: "Tom Hanks", movie: "Apollo 13", year: 1995)
Quote.create!(quote: "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?", character: "Harry Callahan", actor: "Clint Eastwood", movie: "Dirty Harry", year: 1971)
Quote.create!(quote: "You had me at 'hello.'", character: "Dorothy Boyd", actor: "Renée Zellweger", movie: "Jerry Maguire", year: 1996)
Quote.create!(quote: "One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know.", character: "Capt. Geoffrey T. Spaulding", actor: "Groucho Marx", movie: "Animal Crackers", year: 1930)
Quote.create!(quote: "There's no crying in baseball!", character: "Jimmy Dugan", actor: "Tom Hanks", movie: "A League of Their Own", year: 1992)
Quote.create!(quote: "La-dee-da, la-dee-da.", character: "Annie Hall", actor: "Diane Keaton", movie: "Annie Hall", year: 1977)
Quote.create!(quote: "A boy's best friend is his mother.", character: "Norman Bates", actor: "Anthony Perkins", movie: "Psycho", year: 1960)
Quote.create!(quote: "Greed, for lack of a better word, is good.", character: "Gordon Gekko", actor: "Michael Douglas", movie: "Wall Street", year: 1987)
Quote.create!(quote: "Keep your friends close, but your enemies closer.", character: "Michael Corleone", actor: "Al Pacino", movie: "The Godfather Part II", year: 1974)
Quote.create!(quote: "As God is my witness, I'll never be hungry again.", character: "Scarlett O'Hara", actor: "Vivien Leigh", movie: "Gone with the Wind", year: 1939)
Quote.create!(quote: "Well, here's another nice mess you've gotten me into!", character: "Oliver", actor: "Oliver Hardy", movie: "Sons of the Desert", year: 1933)
Quote.create!(quote: "Say 'hello' to my little friend!", character: "Tony Montana", actor: "Al Pacino", movie: "Scarface", year: 1983)
Quote.create!(quote: "What a dump.", character: "Rosa Moline", actor: "Bette Davis", movie: "Beyond the Forest", year: 1949)
Quote.create!(quote: "Mrs. Robinson, you're trying to seduce me. Aren't you?", character: "Benjamin Braddock", actor: "Dustin Hoffman", movie: "The Graduate", year: 1967)
Quote.create!(quote: "Gentlemen, you can't fight in here! This is the War Room!", character: "President Merkin Muffley", actor: "Peter Sellers", movie: "Dr. Strangelove", year: 1964)
Quote.create!(quote: "Elementary, my dear Watson.", character: "Sherlock Holmes", actor: "Basil Rathbone", movie: "The Adventures of Sherlock Holmes", year: 1939)
Quote.create!(quote: "Take your stinking paws off me, you damned dirty ape.", character: "George Taylor", actor: "Charlton Heston", movie: "Planet of the Apes", year: 1968)
Quote.create!(quote: "Of all the gin joints in all the towns in all the world, she walks into mine.", character: "Rick Blaine", actor: "Humphrey Bogart", movie: "Casablanca", year: 1942)
Quote.create!(quote: "Here's Johnny!", character:"Jack Torrance", actor: "Jack Nicholson", movie: "The Shining", year: 1980)
Quote.create!(quote: "They're here!", character: "Carol Anne Freeling", actor: "Heather O'Rourke", movie: "Poltergeist", year: 1982)
Quote.create!(quote: "Is it safe?", character: "Dr. Christian Szell", actor: "Laurence Olivier", movie: "Marathon Man", year: 1976)
Quote.create!(quote: "Wait a minute, wait a minute. You ain't heard nothin' yet!", character: "Jakie Rabinowitz/Jack Robin", actor: "Al Jolson", movie: "The Jazz Singer", year: 1927)
Quote.create!(quote: "No wire hangers, ever!", character: "Joan Crawford", actor: "Faye Dunaway", movie: "Mommie Dearest", year: 1981)
Quote.create!(quote: "Mother of mercy, is this the end of Rico?", character: "Rico Bandello", actor: "Edward G. Robinson", movie: "Little Caesar", year: 1931)
Quote.create!(quote: "Forget it, Jake, it's Chinatown.", character: "Lawrence Walsh", actor: "Joe Mantell", movie: "Chinatown", year: 1974)
Quote.create!(quote: "I have always depended on the kindness of strangers.", character: "Blanche DuBois", actor: "Vivien Leigh", movie: "A Streetcar Named Desire", year: 1951)
Quote.create!(quote: "Hasta la vista, baby.", character: "The Terminator", actor: "Arnold Schwarzenegger", movie: "Terminator 2: Judgment Day", year: 1991)
Quote.create!(quote: "Soylent Green is people!", character: "Det. Robert Thorn", actor: "Charlton Heston", movie: "Soylent Green", year: 1973)
Quote.create!(quote: "Open the pod bay doors, HAL.", character: "Dave Bowman", actor: "Keir Dullea", movie: "2001: A Space Odyssey", year: 1968)
Quote.create!(quote: "Striker: 'Surely you can\'t be serious.' Rumack: 'I am serious … and don\'t call me Shirley.'", character: "Ted Striker and Dr. Rumack", actor: "Robert Hays and Leslie Nielsen", movie: "Airplane!", year: 1980)
Quote.create!(quote: "Yo, Adrian!", character: "Rocky Balboa", actor: "Sylvester Stallone", movie: "Rocky", year: 1976)
Quote.create!(quote: "Hello, gorgeous.", character: "Fanny Brice", actor: "Barbra Streisand", movie: "Funny Girl", year: 1968)
Quote.create!(quote: "Toga! Toga!", character: "John 'Bluto' Blutarsky", actor: "John Belushi", movie: "National Lampoon's Animal House", year: 1978)
Quote.create!(quote: "Listen to them. Children of the night. What music they make.", character: "Count Dracula", actor: "Bela Lugosi", movie: "Dracula", year: 1931)
Quote.create!(quote: "Oh, no, it wasn't the airplanes. It was Beauty killed the Beast.", character: "Carl Denham", actor: "Robert Armstrong", movie: "King Kong", year: 1933)
Quote.create!(quote: "My precious.", character: "Gollum", actor: "Andy Serkis", movie: "The Lord of the Rings: The Two Towers", year: 2002)
Quote.create!(quote: "Attica! Attica!", character: "Sonny Wortzik", actor: "Al Pacino", movie: "Dog Day Afternoon", year: 1975)
Quote.create!(quote: "Sawyer, you're going out a youngster, but you've got to come back a star!", character: "Julian Marsh", actor: "Warner Baxter", movie: "42nd Street", year: 1933)
Quote.create!(quote: "Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!", character: "Ethel Thayer", actor: "Katharine Hepburn", movie: "On Golden Pond", year: 1981)
Quote.create!(quote: "Tell 'em to go out there with all they got and win just one for the Gipper.", character: "George Gipp", actor: "Ronald Reagan", movie: "Knute Rockne, All American", year: 1940)
Quote.create!(quote: "A martini. Shaken, not stirred.", character: "James Bond", actor: "Sean Connery", movie: "Goldfinger", year: 1964)
Quote.create!(quote: "Who's on first.", character: "Dexter", actor: "Bud Abbott", movie: "The Naughty Nineties", year: 1945)
Quote.create!(quote: "Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac...It's in the hole! It's in the hole! It's in the hole!", character: "Carl Spackler", actor: "Bill Murray", movie: "Caddyshack", year: 1980)
Quote.create!(quote: "Life is a banquet, and most poor suckers are starving to death!", character: "Mame Dennis", actor: "Rosalind Russell", movie: "Auntie Mame", year: 1958)
Quote.create!(quote: "I feel the need—the need for speed!", character: "Pete Mitchell and Nick Bradshaw", actor: "Tom Cruise and Anthony Edwards", movie: "Top Gun", year: 1986)
Quote.create!(quote: "Carpe diem. Seize the day, boys. Make your lives extraordinary.", character: "John Keating", actor: "Robin Williams", movie: "Dead Poets Society", year: 1989)
Quote.create!(quote: "Snap out of it!", character: "Loretta Castorini", actor: "Cher", movie: "Moonstruck", year: 1987)
Quote.create!(quote: "My mother thanks you. My father thanks you. My sister thanks you. And I thank you.", character: "George M. Cohan", actor: "James Cagney", movie: "Yankee Doodle Dandy", year: 1942)
Quote.create!(quote: "Nobody puts Baby in a corner.", character: "Johnny Castle", actor: "Patrick Swayze", movie: "Dirty Dancing", year: 1987)
Quote.create!(quote: "I'll get you, my pretty, and your little dog too!", character: "Wicked Witch of the West", actor: "Margaret Hamilton", movie: "The Wizard of Oz", year: 1939)
Quote.create!(quote: "I'm the king of the world!", character: "Jack Dawson", actor: "Leonardo DiCaprio", movie: "Titanic", year: 1997)

puts "Seeding complete!"
